Fix TypeError in scrubX()
This fixes a possible TypeError:

```
TypeError: Cannot use 'in' operator to search for 'x' in null
```

This happens because `null` is also an `object`.